### ISSUE TITLE
Confusion when installing

### ISSUE THREAD

**Issue by AndardsAnimations** [stefanmuller/ldraw2houdini#4]
I'm confuse when it says "C:\Users\<username>\Documents\houdiniXX.X\packages " 
 
but in my laptop the "packages" file is in "C:\Program Files\Side Effects Software\Houdini 20.0.547\packages" so it's in the "Program File" instead of "C:\Users\<username>\Documents\houdiniXX.X\packages.
so i put the "ldraw2houdini-main" in "C:\Program Files\Side Effects Software\Houdini 20.0.547\packages" not "C:\Users\<username>\Documents\houdiniXX.X\packages" and i put the "icons" and "Brickini.shelf" inside "C:\Users\<username>\Documents\houdiniXX.X"

also after i've done with all of that, inside houdini i'm getting this error message when i typed the bird LEGO piece in the installation guide (2546p01)  : 

Traceback (most recent call last):
  File "ldraw_part", line 7, in <module>
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.547/houdini/python3.10libs\houpythonportion\ui.py", line 1137, in decorator
    return func(*args, **kwargs)
  File "C:\PROGRA~1/SIDEEF~1/HOUDIN~1.547/houdini/python3.10libs\hou.py", line 15084, in createNode
    return _hou.Node_createNode(self, node_type_name, node_name, run_init_scripts, load_contents, exact_type_name, force_valid_node_name)
hou.OperationFailed: The attempted operation failed.
Invalid node type name

also other errors when i try the other featurre in the shelf

**Comment by stefanmuller** [comment]
Hey hey,

Please avoid putting random files in random locations. Writing directly into the directory of the software itself is very bad practice and also means, you will have to reinstall the tool every time you update your Houdini version.

Follow the instructions in the readme very closely step by step and don't try to do anything different :)

If the packages folder doesn't exist in C:\Users\\\<username>\Documents\houdiniXX.X you can create the folder yourself and then put the **json** file in there. The json file will then tell Houdini where to find the tool itself and the ldraw library. Make sure that the paths specified in the json file match exactly the location where you downloaded the tool and the ldraw lib.

Hope this helps!
Cheers

**Comment by AndardsAnimations** [comment]
I did it according to the new readme, putting the .json and everything in the packages, make the packages if it's not exist but i still get error it says "the attempted operation failed Invalid node type name"

**Comment by stefanmuller** [comment]
I'm afraid I need more detailed information in order to help.

- Did you delete all the files you put in different locations and started clean from scratch again?
- Are you able to manually create a Brickini LDraw Part node in sop context without using the shelf tool and does it display the basic 2x4 brick?
- What are the exact steps you are performing to get the error?

Can you provide more precise details how you are installing the tool, and where you are putting your files, ideally with screenshots, of each folder and also showing the content of the json file?

**Comment by AndardsAnimations** [comment]
this is all i've been doing

1. I downloaded the files needed
![1](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/41d82fa6-9c62-484e-9bd9-e420f85521d1)

2. I put the "ldraw" library inside "C:\Users\ASUS\Downloads\ldraw2houdini-main\resources"
![2](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/c03a78c9-dc13-43cd-b061-0bfab4ce82a3)

3. I created the "packages" file because it wasn't originally there in "C:\Users\ASUS\Documents\houdini20.0"
![3](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/1ab2f571-4cb3-4bcb-85a7-0381a6cda3d9)

4. I put the "ldraw2houdini-main" and "ldrawhoudini.json" inside the "packages" file
![4](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/dba3fbdd-494a-49f9-9fbf-15f11fffe7e0)

5. I adjust the "ldraw2houdini.json" like in the instruction
![5](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/71837ccc-156c-4a75-9eed-cb66dff58fe5)

6. I put the "brickini.shelf" in the toolbar (C:\Users\ASUS\Documents\houdini20.0\toolbar)

and then i put the "icons" in "icons" 
(C:\Users\ASUS\Documents\houdini20.0\config\Icons)
![6](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/5ef688b4-d9ef-4356-a529-e1417f3c10c5)
![7](https://github.com/stefanmuller/ldraw2houdini/assets/156699759/7d8c490b-dffa-420b-8338-91c43982696f)

**Comment by stefanmuller** [comment]
Okay, but so you aren't actually installing it according to the readme. In fact pretty much every single step you are showing me is different from the readme? Also I don't understand why you are taking random files like the shelf and the icons and putting it in other random folders. The readme never mentioned to do anything like that.

You have to follow the readme. My best advice is to delete everything you did and start from scratch again. Please just go through the steps, follow it very very closely and don't try to do anything different. Same folder paths, same everything.

1. the ldraw2houdini folder needs to go here: C:\Users\ASUS\Documents\git\ldraw2houdini 
2. the ldraw library folder (complete.zip) needs to go here: C:\Users\ASUS\Documents\ldraw
3. the ldraw2houdini.json has to go here: C:\Users\ASUS\Documents\houdini20.0\packages

Please let me know how it goes!

**Comment by AndardsAnimations** [comment]
1. There is no "git" folder in my laptop in
"C:\Users\ASUS\Documents\git\ldraw2houdini" 
There id just 
"C:\Users\ASUS\Documents\HoudiniXX.XX\ldraw2houdini"

2. There is no "ldraw" folder in my "C:\Users\ASUS\Documents" laptop

3. I did put the .json file correctly

And the reason i put the "brickni.shelf" in the "toolbar" is because the brickini is no showing in the houdini shelves, and i put the "icons" the "icons" is because the brickini featture icons is not showing in the brickini menu, also do you have something like Discord? So i can contact you directly because we always replying in ± 24 hours

*Note : i'm using the newest Houdini aprentice non commercial production build

**Comment by stefanmuller** [comment]
Ah yeah, that might be easier. I just sent you a friend request on Discord :)

**Comment by stefanmuller** [comment]
We figured it out on Discord. The files just had to be in the right paths for it to work. Closing this :)
